reference: /path/to/database/genome.fa.gz

assembly:
    wenger: /path/to/assembly1/HG002-denovo-H{hap}.fa
    garg: /path/to/assembly2/HG002-denovo-H{hap}.fa

truth:
    vcf: /path/to/truth/vcf.vcf.gz
    bed: /path/to/truth/regions.bed

vcfanno_config: /path/to/config/conf.toml
