reference: /path/to/database/genome.fa.gz

assembly:
    assembly1: /path/to/assembly1/NA24385-denovo-H{hap}.fa
    assembly2: /path/to/assembly2/NA24385-denovo-H{hap}.fa

truth:
    vcf: /path/to/truth/vcf.vcf.gz
    bed: /path/to/truth/regions.bed

vcfanno_config: /path/to/config/conf.toml
